import { Inter } from 'next/font/google'
import '@/src/stylesheet/all.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-TW">
      <head>
        <script src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}